//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APS.Resources.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur s&apos;est produite sur l&apos;ajout du fichier.
        /// </summary>
        public static string AddFile {
            get {
                return ResourceManager.GetString("AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de l&apos;ajout des rôles.
        /// </summary>
        public static string AjoutRoles {
            get {
                return ResourceManager.GetString("AjoutRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} doit être une chaîne d&apos;une longueur minimale de {1} et d&apos;une longueur maximale de {2}..
        /// </summary>
        public static string ChampLongeurMinMax {
            get {
                return ResourceManager.GetString("ChampLongeurMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} doit être une chaîne d&apos;une longueur maximale de {1}..
        /// </summary>
        public static string ChampLongueurMax {
            get {
                return ResourceManager.GetString("ChampLongueurMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} est obligatoire.
        /// </summary>
        public static string ChampObligatoire {
            get {
                return ResourceManager.GetString("ChampObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; et &apos;{1}&apos; doivent être identiques.
        /// </summary>
        public static string ChampsDifferents {
            get {
                return ResourceManager.GetString("ChampsDifferents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe courant est incorrect ou le nouveau est invalide.
        /// </summary>
        public static string ChangementMotPasseIncorrect {
            get {
                return ResourceManager.GetString("ChangementMotPasseIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative de connexion incorrecte.
        /// </summary>
        public static string ConnectionIncorrect {
            get {
                return ResourceManager.GetString("ConnectionIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le format de l&apos;adresse courriel est invalide.
        /// </summary>
        public static string CourrielInvalide {
            get {
                return ResourceManager.GetString("CourrielInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La création a produit une erreur.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la création de l&apos;utilisateur.
        /// </summary>
        public static string CreationUtilisateur {
            get {
                return ResourceManager.GetString("CreationUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; est inférieur à {1}.
        /// </summary>
        public static string DateInferieur {
            get {
                return ResourceManager.GetString("DateInferieur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; doit être inférieure ou égale à aujourd&apos;hui.
        /// </summary>
        public static string DateInferieureAujourdhui {
            get {
                return ResourceManager.GetString("DateInferieureAujourdhui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; est une date invalide.
        /// </summary>
        public static string DateSQL {
            get {
                return ResourceManager.GetString("DateSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; doit être supérieur ou égal à l&apos;ancienne.
        /// </summary>
        public static string DateSuperieurOuEgalAncienne {
            get {
                return ResourceManager.GetString("DateSuperieurOuEgalAncienne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue qui prévient la suppression.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il ne peut pas avoir deux {0} identiques.
        /// </summary>
        public static string Doublons {
            get {
                return ResourceManager.GetString("Doublons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La grosseur maximale du fichier est 2 Mo.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les types de fichiers acceptés sont: JPG, GIF, PNG et PDF.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; doit avoir le format suivant: {1}.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom d&apos;utilisateur doit uniquement contenir des lettres sans accents et des chiffres.
        /// </summary>
        public static string FormatUsername {
            get {
                return ResourceManager.GetString("FormatUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue..
        /// </summary>
        public static string Generale {
            get {
                return ResourceManager.GetString("Generale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Aucun texte dans Errors.resx ***.
        /// </summary>
        public static string Generique {
            get {
                return ResourceManager.GetString("Generique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de l&apos;exportation de la grille..
        /// </summary>
        public static string GetExportationGrille {
            get {
                return ResourceManager.GetString("GetExportationGrille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; doit avoir au moins {1} caractères.
        /// </summary>
        public static string LongueurMinimum {
            get {
                return ResourceManager.GetString("LongueurMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom du fichier est trop long.
        /// </summary>
        public static string NomFichierTropLong {
            get {
                return ResourceManager.GetString("NomFichierTropLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nouveau mot de passe et la confirmation de mot de passe sont différent.
        /// </summary>
        public static string NouveauMotPasseDifferent {
            get {
                return ResourceManager.GetString("NouveauMotPasseDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; et &apos;{1}&apos; ne peuvent être saisis en même temps.
        /// </summary>
        public static string OuExclusif {
            get {
                return ResourceManager.GetString("OuExclusif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Introuvable.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; doit être compris entre {1} et {2}.
        /// </summary>
        public static string PlageInvalide {
            get {
                return ResourceManager.GetString("PlageInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La valeur &apos;{0}&apos; est invalide pour &apos;{1}&apos;.
        /// </summary>
        public static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un erreur s&apos;est produite dans la production du rapport.
        /// </summary>
        public static string Rapport {
            get {
                return ResourceManager.GetString("Rapport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue pendant la lecture.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; est requis.
        /// </summary>
        public static string Requis {
            get {
                return ResourceManager.GetString("Requis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; est requis lorsque &apos;{1}&apos; est spécifié.
        /// </summary>
        public static string RequisDependant {
            get {
                return ResourceManager.GetString("RequisDependant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; ou &apos;{1}&apos; est requis.
        /// </summary>
        public static string RequisOu {
            get {
                return ResourceManager.GetString("RequisOu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la sauvegarde.
        /// </summary>
        public static string Sauvegarde {
            get {
                return ResourceManager.GetString("Sauvegarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la sauvegarde de l&apos;utilisateur.
        /// </summary>
        public static string SauvegardeUtilisateur {
            get {
                return ResourceManager.GetString("SauvegardeUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; doit être supérieur ou égal à &apos;{1}&apos;.
        /// </summary>
        public static string SuperieurOuEgal {
            get {
                return ResourceManager.GetString("SuperieurOuEgal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la suppression des rôles.
        /// </summary>
        public static string SuppressionRoles {
            get {
                return ResourceManager.GetString("SuppressionRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue qui prévient la mise à jour.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom d&apos;usager entré est déjà utilisé.
        /// </summary>
        public static string UsagerExisteDeja {
            get {
                return ResourceManager.GetString("UsagerExisteDeja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;usager ou le mot de passe fourni est incorrect.
        /// </summary>
        public static string UsagerMotPasseIncorrect {
            get {
                return ResourceManager.GetString("UsagerMotPasseIncorrect", resourceCulture);
            }
        }
    }
}
