//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APS.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune donnée.
        /// </summary>
        public static string AucuneDonnee {
            get {
                return ResourceManager.GetString("AucuneDonnee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous sauvegarder les modifications effectuées?.
        /// </summary>
        public static string ConfirmationNavigation {
            get {
                return ResourceManager.GetString("ConfirmationNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez suivre les instructions dans votre courriel pour réinitialiser votre mot de passe. Si aucun courriel n&apos;est reçu, consulter un administrateur..
        /// </summary>
        public static string CourrielReinitialiserMotPasse {
            get {
                return ResourceManager.GetString("CourrielReinitialiserMotPasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une procédure de réinitialisation de mot de passe est enclanchée pour votre compte utilisateur dans le système. Veuillez suivre le lien suivant pour continuer les démarches:  &lt;a href=&apos;{0}&apos;&gt;réinitialiser&lt;/a&gt; Si vous n&apos;avez pas demandé de réinitialiser votre mot de passe, faites-le savoir à votre adminitrateur..
        /// </summary>
        public static string CourrielReinitialiserMotPasseBody {
            get {
                return ResourceManager.GetString("CourrielReinitialiserMotPasseBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APS: Réinitialiser le mot de passe.
        /// </summary>
        public static string CourrielReinitialiserMotPasseSubject {
            get {
                return ResourceManager.GetString("CourrielReinitialiserMotPasseSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création effectuée.
        /// </summary>
        public static string CreationEffectuee {
            get {
                return ResourceManager.GetString("CreationEffectuee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de début est obligatoire.
        /// </summary>
        public static string DateDebutObligatoire {
            get {
                return ResourceManager.GetString("DateDebutObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de fin des obligatoire.
        /// </summary>
        public static string DateFinObligatoire {
            get {
                return ResourceManager.GetString("DateFinObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin de la liste.
        /// </summary>
        public static string FinDeListe {
            get {
                return ResourceManager.GetString("FinDeListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure avancée de l&apos;Est.
        /// </summary>
        public static string HeureEte {
            get {
                return ResourceManager.GetString("HeureEte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure normale de l&apos;Est.
        /// </summary>
        public static string HeureNormale {
            get {
                return ResourceManager.GetString("HeureNormale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verrouillé.
        /// </summary>
        public static string Lockout {
            get {
                return ResourceManager.GetString("Lockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre compte est vérouillé. Veuillez contacter votre administrateur..
        /// </summary>
        public static string LockoutText {
            get {
                return ResourceManager.GetString("LockoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification effectuée.
        /// </summary>
        public static string ModificationEffectuee {
            get {
                return ResourceManager.GetString("ModificationEffectuee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau statut urgent de {0}.
        /// </summary>
        public static string NouveauStatutUrgent {
            get {
                return ResourceManager.GetString("NouveauStatutUrgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre usager est connecté sur une autre fenêtre.
        /// </summary>
        public static string SessionActive {
            get {
                return ResourceManager.GetString("SessionActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre usager est connecté sur un autre poste. Vous devez vous connecter a nouveau pour continuer.
        /// </summary>
        public static string SessionKill {
            get {
                return ResourceManager.GetString("SessionKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rapport de vente, de performance, et aussi les fonctionnalités des autres utilisateurs…….
        /// </summary>
        public static string TitleGestion {
            get {
                return ResourceManager.GetString("TitleGestion", resourceCulture);
            }
        }
    }
}
